"use client";

import React, { useCallback, useEffect, useRef, useState } from "react";
// ❌ ห้าม import apexcharts ตรง ๆ
// import ApexCharts from "apexcharts";
import { jsPDF } from "jspdf";

import TemplateAlertDocument, {
  ALERT_CHART_ID,
  TemplateAlertDocumentProps,
} from "./TemplateAlertDocument";

// ---- ประเภท template (เผื่อขยายเพิ่มหลายแบบทีหลัง) ----
type TemplateKey = "alert-trend";

type TemplateMeta = {
  systemName?: string;
  generatedBy?: string;
  fileName?: string;
};

type TemplateConfig = {
  key: TemplateKey;
  label: string;
  description: string;
  buildProps: () => {
    document: TemplateAlertDocumentProps;
    meta: TemplateMeta;
  };
};

// ---- ตัวอย่าง template เดียวก่อน ----
const TEMPLATES: TemplateConfig[] = [
  {
    key: "alert-trend",
    label: "Alert Trend Report",
    description: "Line chart of alerts volume by time of day.",
    buildProps: () => ({
      document: {
        title: "AODS Alert Trend Report",
        subtitle: "Alert volume by time of day",
        filters: {
          rangeLabel: "2025-11-01 – 2025-11-30",
          locationLabel: "Head Office",
          cameraLabel: "All Cameras",
          severityLabel: "Critical / High / Medium / Low",
        },
      },
      meta: {
        systemName: "AODS",
        generatedBy: "admin2025",
        fileName: "aods-alert-trend-report.pdf",
      },
    }),
  },
];

const AlertDocumentPreview: React.FC = () => {
  const [selectedKey, setSelectedKey] = useState<TemplateKey>("alert-trend");
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const iframeRef = useRef<HTMLIFrameElement | null>(null);

  const currentTemplate = TEMPLATES.find((t) => t.key === selectedKey)!;
  const { document: documentProps, meta } = currentTemplate.buildProps();

  // cleanup pdf url
  useEffect(() => {
    return () => {
      if (pdfUrl) URL.revokeObjectURL(pdfUrl);
    };
  }, [pdfUrl]);

  const handleGeneratePdf = useCallback(async () => {
    if (isGenerating) return;
    setIsGenerating(true);

    try {
      // ✅ import apexcharts เฉพาะตอนรันบน client
      const apexModule = await import("apexcharts");
      const ApexCharts = apexModule.default;

      // 1) ดึงกราฟจาก ApexCharts เป็น dataURI
      const dataUriResponse = await ApexCharts.exec(ALERT_CHART_ID, "dataURI");
      const imgURI: string | undefined = (dataUriResponse as any)?.imgURI;

      if (!imgURI) {
        alert("ไม่สามารถดึงกราฟจาก ApexCharts ได้");
        return;
      }

      const { title, subtitle, filters } = documentProps;

      const {
        systemName = "AODS",
        generatedBy = "System",
        fileName = "aods-report.pdf",
      } = meta;

      // 2) สร้าง pdf
      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      // header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.text(title || "Alert Report", 20, 20);

      doc.setLineWidth(0.5);
      doc.line(20, 25, 190, 25);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.text(`Generated at: ${new Date().toLocaleString()}`, 20, 33);
      doc.text(`Generated by: ${generatedBy}`, 20, 39);

      // subtitle + filters ใน pdf
      let currentY = 47;

      if (subtitle) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(subtitle, 20, currentY);
        currentY += 6;
      }

      const filterLines: string[] = [];
      if (filters?.rangeLabel)
        filterLines.push(`Range: ${filters.rangeLabel}`);
      if (filters?.locationLabel)
        filterLines.push(`Location: ${filters.locationLabel}`);
      if (filters?.cameraLabel)
        filterLines.push(`Camera: ${filters.cameraLabel}`);
      if (filters?.severityLabel)
        filterLines.push(`Severity: ${filters.severityLabel}`);

      if (filterLines.length > 0) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        filterLines.forEach((line) => {
          doc.text(line, 20, currentY);
          currentY += 5;
        });
        currentY += 4;
      }

      // ตำแหน่งกราฟใน pdf
      const imgX = 20;
      const imgY = Math.max(currentY, 60);
      const imgWidth = 170;
      const imgHeight = 90;

      doc.addImage(imgURI, "PNG", imgX, imgY, imgWidth, imgHeight);

      // footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text(
          `${systemName} · Page ${i} of ${pageCount}`,
          20,
          290
        );
      }

      // สร้าง blob url สำหรับ preview
      const blob = doc.output("blob");
      const url = URL.createObjectURL(blob);

      if (pdfUrl) URL.revokeObjectURL(pdfUrl);
      setPdfUrl(url);

      // ถ้าอยาก save ทันที:
      // doc.save(fileName);
    } catch (err) {
      console.error(err);
      alert("เกิดข้อผิดพลาดในการสร้าง PDF");
    } finally {
      setIsGenerating(false);
    }
  }, [documentProps, meta, pdfUrl, isGenerating]);

  const handleOpenPrintDialog = () => {
    if (!pdfUrl) return;
    window.open(pdfUrl);
  };

  return (
    <div className="flex flex-col gap-6 p-4 md:flex-row md:p-6">
      {/* ===== Left: เลือก template + หน้าตาเอกสาร ===== */}
      <div className="w-full space-y-4 md:w-1/2">
        <div className="flex items-center justify-between gap-4">
          <div>
            <h2 className="text-lg font-semibold text-slate-900">
              Document Template
            </h2>
            <p className="text-xs text-slate-500">
              เลือก template แล้วกด Generate PDF เพื่อดูตัวอย่าง
            </p>
          </div>

          <div className="flex items-center gap-2">
            <label className="text-xs text-slate-500">Template</label>
            <select
              value={selectedKey}
              onChange={(e) =>
                setSelectedKey(e.target.value as TemplateKey)
              }
              className="rounded-md border border-slate-300 bg-white px-2 py-1 text-xs text-slate-800 shadow-sm focus:outline-none focus:ring-2 focus:ring-sky-500"
            >
              {TEMPLATES.map((tpl) => (
                <option key={tpl.key} value={tpl.key}>
                  {tpl.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        <p className="text-xs text-slate-500">
          {currentTemplate.description}
        </p>

        {/* แสดงหน้าตาเอกสาร (Template อย่างเดียว) */}
        <TemplateAlertDocument {...documentProps} />

        <button
          onClick={handleGeneratePdf}
          disabled={isGenerating}
          className="inline-flex items-center rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-800 shadow-sm hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {isGenerating ? "Generating..." : "Generate PDF Preview"}
        </button>
      </div>

      {/* ===== Right: PDF Preview + ปุ่ม Print ===== */}
      <div className="w-full space-y-4 md:w-1/2">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-slate-900">
              PDF Preview
            </h2>
            <p className="text-xs text-slate-500">
              Preview &amp; Print (เหมือน dialog ของ Google/Chrome)
            </p>
          </div>
          <button
            onClick={handleOpenPrintDialog}
            disabled={!pdfUrl}
            className="inline-flex items-center rounded-md bg-sky-600 px-4 py-2 text-sm font-medium text-white shadow-sm disabled:cursor-not-allowed disabled:bg-slate-300"
          >
            Open &amp; Print
          </button>
        </div>

        <div className="h-[520px] overflow-hidden rounded-xl border border-slate-200 bg-slate-50 shadow-inner">
          {pdfUrl ? (
            <iframe
              ref={iframeRef}
              src={pdfUrl}
              className="h-full w-full"
              title="PDF Preview"
            />
          ) : (
            <div className="flex h-full items-center justify-center text-sm text-slate-500">
              กดปุ่ม{" "}
              <span className="mx-1 font-medium">Generate PDF Preview</span>{" "}
              เพื่อดูตัวอย่าง PDF
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AlertDocumentPreview;