"use client";

import { useMemo, useState } from "react";

/* ===== helpers ===== */

const SEVERITY_STYLE: Record<
  string,
  { label: string; color: string; bg: string }
> = {
  low: {
    label: "Low",
    color: "#2563eb",
    bg: "#dbeafe",
  },
  medium: {
    label: "Medium",
    color: "#b45309",
    bg: "#fef3c7",
  },
  high: {
    label: "High",
    color: "#b91c1c",
    bg: "#fee2e2",
  },
  critical: {
    label: "Critical",
    color: "#7f1d1d",
    bg: "#fecaca",
  },
};

/* ===== HTML Template Generator ===== */
function buildAlertHtml(data: {
  cameraName: string;
  severity: string;
  eventName: string;
  location?: string;
  timestamp: string;
}) {
  const sev = SEVERITY_STYLE[data.severity] ?? SEVERITY_STYLE.low;

  return `
<!DOCTYPE html>
<html>
<body style="margin:0;font-family:system-ui,Segoe UI,Arial;background:#f8fafc;padding:24px;">
  <div style="max-width:560px;margin:auto;background:white;border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.06);overflow:hidden;">
    
    <!-- Header -->
    <div style="background:#0f172a;color:white;padding:16px 18px;">
      <div style="font-size:18px;font-weight:600;">
        🚨 AODS Alert Notification
      </div>
      <div style="font-size:12px;color:#94a3b8;">
        AI Object Detection System
      </div>
    </div>

    <!-- Body -->
    <div style="padding:20px;color:#020617;font-size:14px;">
      <p style="margin-top:0">
        ระบบตรวจพบเหตุการณ์ที่ต้องตรวจสอบจากกล้อง:
      </p>

      <table style="width:100%;border-collapse:collapse;line-height:1.6;">
        <tr>
          <td style="width:120px;color:#64748b;">Camera</td>
          <td><strong>${data.cameraName}</strong></td>
        </tr>
        <tr>
          <td style="color:#64748b;">Event</td>
          <td>${data.eventName}</td>
        </tr>
        <tr>
          <td style="color:#64748b;">Severity</td>
          <td>
            <span style="
              padding:4px 12px;
              border-radius:999px;
              background:${sev.bg};
              color:${sev.color};
              font-weight:600;
              font-size:12px;">
              ${sev.label.toUpperCase()}
            </span>
          </td>
        </tr>
        <tr>
          <td style="color:#64748b;">Datetime</td>
          <td>${new Date(data.timestamp).toLocaleString()}</td>
        </tr>
        ${data.location
      ? `
        <tr>
          <td style="color:#64748b;">Location</td>
          <td>${data.location}</td>
        </tr>
        `
      : ""
    }
      </table>

      <!-- CTA -->
      <div style="margin-top:18px;text-align:center;">
        <a href="http://localhost:3000/dashboard"
           style="
             display:inline-block;
             padding:10px 18px;
             background:#2563eb;
             color:white;
             border-radius:10px;
             text-decoration:none;
             font-weight:500;
             font-size:13px;
           ">
           Open Dashboard
        </a>
      </div>
    </div>

    <!-- Footer -->
    <div style="
      background:#f1f5f9;
      padding:12px 18px;
      font-size:11px;
      color:#64748b;
      text-align:center;">
      This email was automatically generated by AODS WorkQuest Platform.
    </div>

  </div>
</body>
</html>
  `;
}

/* ===== React Component ===== */

export default function TestAlertMailPage() {
  const [to, setTo] = useState("");
  const [cameraName, setCamera] = useState("Gate Entrance Cam 01");
  const [eventName, setEvent] = useState("Tamper Detected");
  const [severity, setSeverity] = useState("critical");
  const [location, setLocation] = useState("Head Office Front Gate");

  const timestamp = new Date().toISOString();

  const htmlPreview = useMemo(
    () =>
      buildAlertHtml({
        cameraName,
        eventName,
        severity,
        location,
        timestamp,
      }),
    [cameraName, eventName, severity, location]
  );

  async function handleSend() {
    await fetch('/api/mail/alert', {
      method: "POST",
      credentials: "include",
      cache: "no-store",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        to,
        subject: `[AODS ALERT] ${eventName}`,
        html: htmlPreview,
      }),
    });

    alert("✅ Alert email sent!");
  }

  return (
    <div className="max-w-5xl mx-auto py-10 px-4">
      <h1 className="text-2xl font-semibold mb-3">
        🚀 Test AODS Email Alert Template
      </h1>

      {/* ===== FORM ===== */}
      <div className="grid md:grid-cols-[350px_1fr] gap-6">
        <div className="space-y-3 border rounded-xl p-4 bg-white">
          <input
            value={to}
            onChange={(e) => setTo(e.target.value)}
            placeholder="Send to email..."
            className="input w-full border px-3 py-2 rounded"
          />

          <input
            value={cameraName}
            onChange={(e) => setCamera(e.target.value)}
            placeholder="Camera name"
            className="input w-full border px-3 py-2 rounded"
          />

          <input
            value={eventName}
            onChange={(e) => setEvent(e.target.value)}
            placeholder="Event name"
            className="input w-full border px-3 py-2 rounded"
          />

          <select
            value={severity}
            onChange={(e) => setSeverity(e.target.value)}
            className="input w-full border px-3 py-2 rounded"
          >
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
            <option value="critical">Critical</option>
          </select>

          <input
            value={location}
            onChange={(e) => setLocation(e.target.value)}
            placeholder="Location"
            className="input w-full border px-3 py-2 rounded"
          />

          <button
            onClick={handleSend}
            className="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition"
          >
            Send Alert Email
          </button>
        </div>

        {/* ===== PREVIEW ===== */}
        <div className="border rounded-xl overflow-hidden bg-slate-100">
          <iframe
            title="Email Preview"
            srcDoc={htmlPreview}
            className="w-full h-[580px] border-none bg-white"
          />
        </div>
      </div>
    </div>
  );
}