"use client";

import { useMemo, useState } from "react";

/* ===== helpers ===== */

function escapeHtml(str: string) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/* ===== HTML Template Generator (ข้อความใน Card อย่างเดียว) ===== */
function buildMessageHtml(data: { subject: string; message: string }) {
  const safeSubject = escapeHtml(data.subject || "AODS Notification");
  const safeMessage = escapeHtml(data.message || "");

  return `
<!DOCTYPE html>
<html>
  <body style="margin:0;font-family:system-ui,Segoe UI,Arial;background:#f8fafc;padding:24px;">
    <div style="max-width:560px;margin:auto;background:white;border-radius:16px;box-shadow:0 10px 30px rgba(15,23,42,.16);overflow:hidden;border:1px solid #e2e8f0;">
      
      <!-- Header -->
      <div style="background:linear-gradient(135deg,#0f172a,#1e293b);color:white;padding:18px 20px;">
        <div style="font-size:18px;font-weight:600;display:flex;align-items:center;gap:8px;">
          <span style="font-size:20px;">✉️</span>
          <span>${safeSubject}</span>
        </div>
        <div style="font-size:12px;color:#cbd5f5;margin-top:4px;">
          AODS · AI Object Detection & Monitoring Platform
        </div>
      </div>

      <!-- Body -->
      <div style="padding:20px 22px 18px;color:#020617;font-size:14px;line-height:1.7;background:#f9fafb;">
        <p style="margin:0 0 10px 0;color:#475569;font-size:13px;">
          คุณได้รับข้อความใหม่จากระบบ AODS:
        </p>

        <!-- Message Card -->
        <div style="
          margin-top:4px;
          padding:14px 16px;
          border-radius:14px;
          background:#ffffff;
          border:1px solid #e2e8f0;
          box-shadow:0 4px 14px rgba(15,23,42,.05);
          font-size:13px;
          color:#0f172a;
          white-space:pre-line;
        ">
          ${safeMessage}
        </div>

        <!-- Meta -->
        <div style="margin-top:14px;font-size:11px;color:#94a3b8;">
          Sent via AODS Message Center
        </div>
      </div>

      <!-- Footer -->
      <div style="
        background:#f1f5f9;
        padding:10px 18px;
        font-size:11px;
        color:#64748b;
        text-align:center;
        border-top:1px solid #e2e8f0;
      ">
        This email was automatically generated by AODS WorkQuest Platform.
      </div>

    </div>
  </body>
</html>
  `;
}

/* ===== React Component ===== */

export default function TestMessageMailPage() {
  const [to, setTo] = useState("");
  const [subject, setSubject] = useState("[AODS] New Message");
  const [message, setMessage] = useState(
    "สวัสดีค่ะ/ครับ,\n\nนี่คือข้อความตัวอย่างจากระบบ AODS คุณสามารถแก้ไขข้อความนี้ได้ตามต้องการ 😊"
  );

  const htmlPreview = useMemo(
    () =>
      buildMessageHtml({
        subject,
        message,
      }),
    [subject, message]
  );

  async function handleSend() {
    await fetch("/api/mail/alert", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        to,
        subject,
        html: htmlPreview,
      }),
    });

    alert("✅ Message email sent!");
  }

  return (
    <div className="max-w-5xl mx-auto py-10 px-4">
      <h1 className="text-2xl font-semibold mb-1">
        ✉️ Test AODS Message Card Email
      </h1>
      <p className="text-sm text-slate-500 mb-4">
        ใส่ Subject และ Message แล้วส่งเป็นอีเมลแบบการ์ดข้อความสวย ๆ
      </p>

      {/* ===== FORM + PREVIEW ===== */}
      <div className="grid md:grid-cols-[340px_1fr] gap-6">
        {/* Form */}
        <div className="space-y-3 border rounded-2xl p-4 bg-white shadow-sm">
          <div className="space-y-1">
            <label className="text-xs font-medium text-slate-600">
              Send To
            </label>
            <input
              value={to}
              onChange={(e) => setTo(e.target.value)}
              placeholder="email@example.com"
              className="w-full border border-slate-200 px-3 py-2 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/40 focus:border-blue-500"
            />
          </div>

          <div className="space-y-1">
            <label className="text-xs font-medium text-slate-600">
              Subject
            </label>
            <input
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder="[AODS] New Message"
              className="w-full border border-slate-200 px-3 py-2 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/40 focus:border-blue-500"
            />
          </div>

          <div className="space-y-1">
            <label className="text-xs font-medium text-slate-600">
              Message
            </label>
            <textarea
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder="พิมพ์ข้อความที่ต้องการส่ง..."
              rows={8}
              className="w-full border border-slate-200 px-3 py-2 rounded-lg text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-500/40 focus:border-blue-500"
            />
          </div>

          <button
            onClick={handleSend}
            className="w-full bg-blue-600 text-white py-2.5 rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors"
          >
            ส่งอีเมลข้อความ (Message Email)
          </button>
        </div>

        {/* Preview */}
        <div className="border rounded-2xl overflow-hidden bg-slate-100 shadow-inner">
          <iframe
            title="Email Preview"
            srcDoc={htmlPreview}
            className="w-full h-[580px] border-none bg-white"
          />
        </div>
      </div>
    </div>
  );
}
